CREATE TABLE [dbo].[Page](
	[PageId] [INT] IDENTITY(1,1) NOT NULL,
	[PageLink] [VARCHAR](500) NULL,
	[PageName] [VARCHAR](500) NULL,
 CONSTRAINT [PK_Page_1] PRIMARY KEY CLUSTERED 
(
	[PageId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
